const KEY="vm-lounge-2026-v2";
const id=()=>crypto.randomUUID?crypto.randomUUID():"id"+Date.now()+Math.random();
const seed={user:{name:"Thomas",coins:10000},selected:[],bets:[],activity:["Velkommen til VM Lounge 2026.","Demo-kamper er lagt inn."],matches:[{id:id(),home:"Mexico",away:"Sør-Afrika",flags:["🇲🇽","🇿🇦"],time:"2026-06-11T21:00",status:"Åpningskamp",odds:{home:1.95,draw:3.4,away:4.1}},{id:id(),home:"Canada",away:"Qatar",flags:["🇨🇦","🇶🇦"],time:"2026-06-12T02:00",status:"Gruppekamp",odds:{home:2.2,draw:3.15,away:3.3}},{id:id(),home:"USA",away:"Japan",flags:["🇺🇸","🇯🇵"],time:"2026-06-12T20:00",status:"Recommended",odds:{home:2.05,draw:3.35,away:3.6}},{id:id(),home:"Argentina",away:"Frankrike",flags:["🇦🇷","🇫🇷"],time:"2026-06-14T21:00",status:"Featured",odds:{home:2.45,draw:3.2,away:2.75}},{id:id(),home:"Brasil",away:"Tyskland",flags:["🇧🇷","🇩🇪"],time:"2026-06-15T18:00",status:"Classic",odds:{home:2.25,draw:3.3,away:3.05}}],forum:[{id:id(),title:"Hvem blir toppscorer?",text:"Jeg tror Mbappé eller Haaland hvis Norge kommer langt. Hva tror dere?",author:"Thomas",likes:4},{id:id(),title:"Regler for vennekonkurransen",text:"Forslag: 10 000 coins start, maks 2 000 coins per kamp, og toppliste etter finalen.",author:"Admin",likes:7}],chat:{public:[{from:"Admin",text:"Velkommen til offentlig VM-chat!"},{from:"Elise",text:"Dette blir gøy 😄"}],Elise:[{from:"Elise",text:"Klar for VM?"}],Kjell:[{from:"Kjell",text:"Jeg følger leaderboardet!"}],Heidi:[{from:"Heidi",text:"Heia Norge!"}]},leaderboard:[{name:"Thomas",coins:10000},{name:"Elise",coins:9700},{name:"Kjell",coins:9300},{name:"Heidi",coins:9000}]};
let state=load(),room="public";
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(seed)}catch{return structuredClone(seed)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function money(n){return Number(n||0).toLocaleString("nb-NO")}
function safe(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}
function time(t){let d=new Date(t);return isNaN(d)?t:d.toLocaleString("nb-NO",{weekday:"short",day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"})}
function toast(t){let el=document.getElementById("toast");el.textContent=t;el.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>el.hidden=true,2400)}
function page(p){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));document.getElementById(p)?.classList.add("active");document.querySelectorAll("[data-page]").forEach(x=>{let active=x.dataset.page===p;x.classList.toggle("active",active);active?x.setAttribute("aria-current","page"):x.removeAttribute("aria-current")});document.body.classList.remove("menu-open");scrollTo({top:0,behavior:"smooth"})}
function syncCoins(){["coinsRail","coinsProfile"].forEach(x=>{let e=document.getElementById(x);if(e)e.textContent=money(state.user.coins)});document.getElementById("profileName").textContent=state.user.name}
function card(m){let sel=state.selected.find(s=>s.matchId===m.id);let opts=[["home","1",m.home,m.odds.home],["draw","X","Uavgjort",m.odds.draw],["away","2",m.away,m.odds.away]];return `<article class="match searchItem"><div class="mtop"><span>VM 2026</span><span>${safe(m.status)} • ${time(m.time)}</span></div><div class="teams"><div class="team"><div class="flag">${m.flags?.[0]||"⚽"}</div><strong>${safe(m.home)}</strong></div><div class="vs">VS</div><div class="team away"><div class="flag">${m.flags?.[1]||"⚽"}</div><strong>${safe(m.away)}</strong></div></div><div class="odds">${opts.map(o=>`<button class="odd ${sel?.pick===o[0]?"selected":""}" data-match="${m.id}" data-pick="${o[0]}"><small>${o[1]}</small><b>${Number(o[3]).toFixed(2)}</b></button>`).join("")}</div></article>`}
function renderMatches(){document.getElementById("homeMatches").innerHTML=state.matches.slice(0,3).map(card).join("");document.getElementById("matchList").innerHTML=state.matches.map(card).join("");document.querySelectorAll(".odd").forEach(b=>b.onclick=()=>pick(b.dataset.match,b.dataset.pick))}
function pick(matchId,pick){let m=state.matches.find(x=>x.id===matchId);if(!m)return;state.selected=state.selected.filter(s=>s.matchId!==matchId);let label=pick==="home"?m.home:pick==="away"?m.away:"Uavgjort";state.selected.push({matchId,pick,label,title:`${m.home} - ${m.away}`,odds:m.odds[pick]});save();renderMatches();renderSlip()}
function renderSlip(){let empty=document.getElementById("emptySlip"),body=document.getElementById("slipBody"),items=document.getElementById("slipItems");let has=state.selected.length>0;empty.hidden=has;body.hidden=!has;if(!has){document.getElementById("homeWin").textContent="0";return}items.innerHTML=state.selected.map(s=>`<div class="selection"><b>${safe(s.label)}</b><small>${safe(s.title)} • odds ${Number(s.odds).toFixed(2)}</small></div>`).join("");let odds=state.selected.reduce((a,s)=>a*Number(s.odds),1);let stake=Number(document.getElementById("stake")?.value||100);document.getElementById("totalOdds").textContent=odds.toFixed(2);document.getElementById("possibleWin").textContent=money(Math.round(odds*stake));document.getElementById("homeWin").textContent=money(Math.round(odds*stake))}
function placeBet(){let stake=Number(document.getElementById("stake").value||0);if(!state.selected.length)return toast("Velg odds først.");if(stake<10)return toast("Minimum innsats er 10 coins.");if(stake>state.user.coins)return toast("Du har ikke nok coins.");let odds=state.selected.reduce((a,s)=>a*Number(s.odds),1);state.user.coins-=stake;state.bets.unshift({id:id(),selections:structuredClone(state.selected),stake,odds,possibleWin:Math.round(stake*odds),status:"Aktiv"});state.activity.unshift(`${state.user.name} plasserte et bet på ${money(stake)} coins.`);let me=state.leaderboard.find(x=>x.name===state.user.name);me?me.coins=state.user.coins:state.leaderboard.push({name:state.user.name,coins:state.user.coins});state.selected=[];save();render();toast("Bet plassert!")}
function renderLeaderboard(){let sorted=[...state.leaderboard].sort((a,b)=>b.coins-a.coins);document.getElementById("leaderboard").innerHTML=sorted.map((r,i)=>`<div class="row"><div class="badge">${i+1}</div><div><b>${safe(r.name)}</b><small>VM-tipster</small></div><b>${money(r.coins)}</b></div>`).join("");let rank=sorted.findIndex(x=>x.name===state.user.name)+1;document.getElementById("rankNo").textContent=rank||"-"}
function renderActivity(){document.getElementById("activity").innerHTML=state.activity.slice(0,8).map(x=>`<div class="row"><div class="badge">•</div><div><b>${safe(x)}</b><small>nå</small></div><small>VM</small></div>`).join("")}
function renderForum(){document.getElementById("posts").innerHTML=state.forum.map(p=>`<article class="post searchItem"><h3>${safe(p.title)}</h3><p>${safe(p.text)}</p><div class="meta"><span>Av ${safe(p.author)}</span><span>♡ ${p.likes||0}</span></div></article>`).join("");document.getElementById("postCount").textContent=state.forum.filter(p=>p.author===state.user.name).length}
function renderChat(){document.getElementById("roomTitle").textContent=room==="public"?"Offentlig chat":"Privat chat med "+room;let box=document.getElementById("messages");box.innerHTML=(state.chat[room]||[]).map(m=>`<div class="msg ${m.from===state.user.name?"me":""}"><small>${safe(m.from)}</small>${safe(m.text)}</div>`).join("");box.scrollTop=box.scrollHeight}
function renderProfile(){document.getElementById("activeBets").textContent=state.bets.filter(b=>b.status==="Aktiv").length;let mine=document.getElementById("myBets");mine.innerHTML=state.bets.length?state.bets.map(b=>`<div class="row"><div class="badge">◉</div><div><b>${b.selections.map(s=>safe(s.label)).join(" + ")}</b><small>${b.selections.map(s=>safe(s.title)).join(", ")}</small></div><div><b>${money(b.possibleWin)}</b><small>${safe(b.status)}</small></div></div>`).join(""):`<div class="empty">Du har ingen bets enda.</div>`}
function renderBoard(){let pieces=["♜","♞","♝","♛","♚","♝","♞","♜","♟","♟","♟","♟","♟","♟","♟","♟","","","","","","","","","","","","♙","","","","","","","","","♙","","","","","","♘","","","♘","","","♙","♙","♙","","","♙","♙","♙","♖","","♗","♕","♔","♗","","♖"];document.getElementById("board").innerHTML=pieces.map((p,i)=>`<div class="sq ${((Math.floor(i/8)+i)%2)?"dark":"light"}">${p}</div>`).join("")}
function render(){syncCoins();renderMatches();renderSlip();renderLeaderboard();renderActivity();renderForum();renderChat();renderProfile();renderBoard()}

document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>page(b.dataset.page));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>page(b.dataset.go));document.getElementById("hamb").onclick=()=>document.body.classList.toggle("menu-open");document.getElementById("stake").oninput=renderSlip;document.getElementById("clearSlip").onclick=()=>{state.selected=[];save();renderMatches();renderSlip()};document.getElementById("placeBet").onclick=placeBet;document.getElementById("matchForm").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);state.matches.unshift({id:id(),home:f.get("home"),away:f.get("away"),flags:["⚽","⚽"],time:f.get("time"),status:"Ny",odds:{home:+f.get("oh"),draw:+f.get("ox"),away:+f.get("oa")}});state.activity.unshift(`Ny kamp lagt inn: ${f.get("home")} - ${f.get("away")}`);e.target.reset();save();render();toast("Kamp lagt til")};document.getElementById("postForm").onsubmit=e=>{e.preventDefault();let title=document.getElementById("postTitle").value.trim(),text=document.getElementById("postText").value.trim();if(!title||!text)return;state.forum.unshift({id:id(),title,text,author:state.user.name,likes:0});state.activity.unshift(`${state.user.name} publiserte i forumet.`);e.target.reset();save();render();toast("Publisert")};document.querySelectorAll(".room").forEach(b=>b.onclick=()=>{document.querySelectorAll(".room").forEach(x=>x.classList.remove("active"));b.classList.add("active");room=b.dataset.room;renderChat()});document.getElementById("chatForm").onsubmit=e=>{e.preventDefault();let input=document.getElementById("chatInput"),text=input.value.trim();if(!text)return;state.chat[room]??=[];state.chat[room].push({from:state.user.name,text});input.value="";save();renderChat()};document.getElementById("loginBtn").onclick=()=>{let n=prompt("Skriv brukernavn:",state.user.name);if(!n)return;state.user.name=n.trim();if(!state.leaderboard.find(x=>x.name===state.user.name))state.leaderboard.push({name:state.user.name,coins:state.user.coins});save();render();toast("Logget inn som "+state.user.name)};document.getElementById("registerBtn").onclick=()=>{let n=prompt("Velg brukernavn:");if(!n)return;state.user={name:n.trim(),coins:10000};state.leaderboard.push({name:state.user.name,coins:10000});save();render();toast("Bruker opprettet")};document.getElementById("editName").onclick=()=>{let n=prompt("Nytt navn:",state.user.name);if(!n)return;state.user.name=n.trim();save();render()};document.getElementById("resetBtn").onclick=()=>{if(confirm("Nullstille demo-data på denne enheten?")){localStorage.removeItem(KEY);state=structuredClone(seed);save();render();toast("Nullstilt")}};document.getElementById("search").oninput=e=>{let q=e.target.value.toLowerCase();document.querySelectorAll(".searchItem").forEach(x=>x.style.display=x.textContent.toLowerCase().includes(q)?"":"none")};
render();
